"""empty message

Revision ID: 347ab685824e
Revises: 299253f23d87
Create Date: 2017-06-10 10:20:34.952000

"""

# revision identifiers, used by Alembic.
revision = '347ab685824e'
down_revision = '299253f23d87'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_programs')
    op.alter_column('docker_images', 'is_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('docker_images', 'is_ssh_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('docker_images', 'is_vnc_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('homework', 'deadline',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('homework', 'description',
               existing_type=mysql.TEXT(collation=u'utf8_unicode_ci'),
               nullable=True)
    op.alter_column('homework', 'title',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=256),
               nullable=True)
    op.drop_index('course_id', table_name='questions')
    op.alter_column('submit_problem', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(u'user_questions_ibfk_1', 'user_questions', type_='foreignkey')
    op.alter_column('users', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_foreign_key(u'user_questions_ibfk_1', 'user_questions', 'users', ['user_id'], ['id'])
    op.alter_column('submit_problem', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('course_id', 'questions', ['user_id'], unique=False)
    op.alter_column('homework', 'title',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=256),
               nullable=False)
    op.alter_column('homework', 'description',
               existing_type=mysql.TEXT(collation=u'utf8_unicode_ci'),
               nullable=False)
    op.alter_column('homework', 'deadline',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('docker_images', 'is_vnc_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('docker_images', 'is_ssh_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('docker_images', 'is_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.create_table('lab_programs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('source_code', mysql.TEXT(), nullable=False),
    sa.Column('default_code', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
