"""empty message

Revision ID: 424dd5fc4e1b
Revises: 1506c4df4d52
Create Date: 2017-09-03 17:00:57.887000

"""

# revision identifiers, used by Alembic.
revision = '424dd5fc4e1b'
down_revision = '1506c4df4d52'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_programs')
    op.alter_column('docker_images', 'is_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('docker_images', 'is_ssh_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('docker_images', 'is_vnc_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('notifications_receivers', 'notification_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('notifications_receivers', 'receiver_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('programs', 'can_evaluate',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_index('course_id', table_name='questions')
    op.alter_column('submit_programs', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'submit_programs', 'users', ['uid'], ['id'])
    op.alter_column('users', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'student_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('users', 'student_type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'-1'"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'student_type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'-1'"))
    op.alter_column('users', 'student_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('users', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_constraint(None, 'submit_programs', type_='foreignkey')
    op.alter_column('submit_programs', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('course_id', 'questions', ['user_id'], unique=False)
    op.alter_column('programs', 'can_evaluate',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('notifications_receivers', 'receiver_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('notifications_receivers', 'notification_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('docker_images', 'is_vnc_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('docker_images', 'is_ssh_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('docker_images', 'is_running',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.create_table('lab_programs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('source_code', mysql.TEXT(), nullable=False),
    sa.Column('default_code', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
