"""empty message

Revision ID: 8e2375f5b299
Revises: 7817e631ed63
Create Date: 2017-05-16 13:10:46.035000

"""

# revision identifiers, used by Alembic.
revision = '8e2375f5b299'
down_revision = '7817e631ed63'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('course_id', table_name='questions')
    op.alter_column('submit_problem', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(u'user_questions_ibfk_1', 'user_questions', type_='foreignkey')
    op.alter_column('users', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_foreign_key(u'user_questions_ibfk_1', 'user_questions', 'users', ['user_id'], ['id'])
    op.alter_column('submit_problem', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('course_id', 'questions', ['user_id'], unique=False)
    ### end Alembic commands ###
