"""empty message

Revision ID: e91e329650f8
Revises: 347ab685824e
Create Date: 2017-07-21 13:56:13.433000

"""

# revision identifiers, used by Alembic.
revision = 'e91e329650f8'
down_revision = '347ab685824e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('course_id', table_name='questions')
    op.alter_column('submit_programs', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'submit_programs', 'users', ['uid'], ['id'])
    op.alter_column('users', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'student_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('users', 'student_type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'-1'"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'student_type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'-1'"))
    op.alter_column('users', 'student_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('users', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_constraint(None, 'submit_programs', type_='foreignkey')
    op.alter_column('submit_programs', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('course_id', 'questions', ['user_id'], unique=False)
    ### end Alembic commands ###
